POST http://localhost:3000/location/new HTTP/1.1
Content-Type: application/json

{
  "location": "Seoul"
}

###
PUT http://localhost:3000/location/63dbea7b5b6e86ae68e65995/bar/new HTTP/1.1
Content-Type: application/json

{
    "name": "Bo Peeps",
    "cuisine": "Cocktails",
    "rating": 10
}

###
DELETE http://localhost:3000/location/63dbea7b5b6e86ae68e65995

###
GET http://localhost:3000/location/63db4c06d33b3a569b3d27b3

###
DELETE http://localhost:3000/location/63db4c06d33b3a569b3d27b3/restaurant/nami nori

###
DELETE http://localhost:3000/location/63db4c06d33b3a569b3d27b3/bar/BoPeePs

###
GET http://localhost:3000/locations/